### ISSUE TITLE
👋 Do you know a sollution?

### ISSUE THREAD

**Issue by Siemienik** [fatawesome/vue-next-isce-issue#1]
Hi @fatawesome, do you know why this happens and how to fix that?

Kindly regards

**Comment by fatawesome** [comment]
Hey! Yep, the reason is that we provide two instances of Vue, while it should be a singleton. See [this commit](https://github.com/fatawesome/vue-next-isce-issue/commit/c462c1d5d306fb577f980c3e3b0bf4509ead3b21) for a fix.

**Comment by Siemienik** [comment]
Thank you :)
